name: toma
version: 0.8
build-type: Simple
cabal-version: >=1.10

executable toma
  ghc-options: -O -Wall
  build-depends:
    base,
    containers,
    parsec,
    process,
    optparse-applicative,
    split,
    multiset,
    vector,
    text,
    directory,
    filepath,
    heaps,
    time
  default-language: Haskell2010
  main-is: Main.hs
  other-modules:
    Term
    Rule
    KBO
    Precedence
    Signature
    Weight
    ARI
    Parsing
    Rewriting
    Proof
    TPTP
    CP
    Discount
    ReductionOrder
    IntMultiSet
    TSTP
    Algebra
    Linear
    SMT
    SPO
    LinearEncoding
    SPOEncoding
    GWPO
    GWPOEncoding
    MGWPO
    MGWPOEncoding
    KBOEncoding
    Indexing
    RewritingIndexing
    CPIndexing
    AC
    Equation
    Logging
    LPO
    Connectedness
    INF
    PrecedenceEncoding
    MaxPlus
    MaxPlusEncoding
